### PR TITLE
Integrate fixes for windows users

### PR DESCRIPTION
**Pull request by jmartsch**
Don´t know what to do about the tar replacement in git-utils.coffee (i used the copy command instead). Maybe you take it, maybe you leave it.

### CODE REVIEW

**Comment by larrybotha** [comment]
haha, thanks @jmartsch 

I'll take a look at the copy command, as you've validated it works. I may ask you to validate my udpates.

For the setup.sh I may write a small node app that uses shelljs to rather perform all those tasks to keep it system agnostic.

**Comment by jmartsch** [comment]
I will validate your updates when they arrive.  I am also planning to integrate bourbon.io mixins and Susy as SCSS Framework. Are you interested in this?

**Comment by larrybotha** [comment]
currently we use the [inuit branch of my framework](https://github.com/larrybotha/styleguide/tree/inuit), but it'd be cool if this generator were flexible enough for devs to select from a list a preferred framework.

**Comment by larrybotha** [comment]
please check to see if npm's preinstall now works on Windows on branch [hotfix/0.2.13](https://github.com/fixate/generator-fixate-pw/tree/hotfix/0.2.13).

I've changed the script to rather run as a node app. Everything seems to be working fine on my side, after fighting with a ton of node modules that I had to manually uninstall and reinstall.

I'll merge your changes into the hotfix before releasing into master.

**Comment by jmartsch** [comment]
Hi Larry,
everything seems to work fine now. Although I got some errors when i ran yo fixate-pw. I list them here, but left some lines out:
```
    info Installing ProcessWire site profile...
Cloning into 'W:\wamp\www\generator-fixate-pw\app\templates\.gitcache\fixate\pw-mvc-boilerplate-site-profile'...
W:\wamp\www\generator-fixate-pw\app\templates\.gitcache\fixate\pw-mvc-boilerplate-site-profile W:\wamp\www\fixate-hotfix
From https://github.com/fixate/pw-mvc-boilerplate-site-profile
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Your branch is up-to-date with 'origin/master'.
Already on 'master'
cp: dest file already exists: W:\wamp\www\fixate-hotfix\src\README.md

W:\wamp\www\fixate-hotfix
W:\wamp\www\fixate-hotfix\src W:\wamp\www\fixate-hotfix
rm: no such file or directory: .gitignore

√ OK
     info Installing ProcessWire MVC boilerplate...
W:\wamp\www\generator-fixate-pw\app\templates\.gitcache\fixate\pw-boilerplate W:\wamp\www\fixate-hotfix
From https://github.com/fixate/pw-boilerplate
 * branch            master     -> FETCH_HEAD
Already up-to-date.
Your branch is up-to-date with 'origin/master'.
Already on 'master'
cp: dest file already exists: W:\wamp\www\fixate-hotfix\src\site\templates\admin.php

Your bundle is complete!
Use `bundle show [gemname]` to see where a bundled gem is installed.
mv: no such file or directory: ./scss
```
I still have to run npm install & bower install by myself.
npm install failed:
```
> execSync@1.0.2 install W:\wamp\www\fixate-hotfix\node_modules\execSync
> node install.js

[execsync v1.0.2] Attempting to compile native extensions.
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
[execSync v1.0.2]
    Native code compile failed!!
    Will try to use win32 extension.
shelljs@0.4.0 node_modules\shelljs

execSync@1.0.2 node_modules\execSync
└── temp@0.5.1 (rimraf@2.1.4)
[Error: no errorW:\wamp\www\fixate-hotfix\node_modules\execSync\win32\v0.10\shell.node]

W:\wamp\www\fixate-hotfix\node_modules\execSync\index.js:24
      throw new Error('execSync incompatible with installed nodejs');
            ^
Error: execSync incompatible with installed nodejs
    at Object.<anonymous> (W:\wamp\www\fixate-hotfix\node_modules\execSync\index.js:24:13)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (W:\wamp\www\fixate-hotfix\setup.js:2:14)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
npm ERR! weird error 8
npm ERR! not ok code 0
```

As you can see on execSync´s github page the project is no longer maintained, and both iojs and node.js v0.12 have execSync function, so the error ```Error: execSync incompatible with installed nodejs``` occured.

**Comment by larrybotha** [comment]
those cp and rm errors are likely from before we reordered the assets structure; I'll deal with them soon.

it's throwing `execSync incompatible with installed nodejs`, so it looks like your version of node may be incompatible.

execSync's compatibility, according to their [package.json](https://github.com/mgutz/execSync/blob/master/package.json#L16), is any node before 0.11.

if you run `node -v` what are you getting? You could perhaps install nvm, and switch to a compatible version.

**Pull request closed without merging**
